### PR TITLE
Ljiljana-Populate DB with initial data

### PR DESCRIPTION
**Pull request by Ljanjic**
Populate DB with initial data by working on Registration, Login, Logout, and Deleting account features, and CRUD for the activity.

### CODE REVIEW

**Comment by TammamWafai** [comment]
Great job Ljiljana! I see you worked on many features. 

1. It's good if we work on one feature in a branch
2. Keeping branch names and commit messages self-descriptive is a good practice
3. You can add some error handling to **comparePassowrd** as it's an async function, for example: 
```
UserSchema.methods.comparePassword = async function (enteredPassword) {
  try {
    const isMatch = await bcrypt.compare(enteredPassword, this.password);
    return isMatch;
  } catch (error) {
    throw error;
  }
};
```
4. In UserSchema, we can add a "unique" attribute to (username and email) with a custom error message to avoid duplicate entries:
`username: {
    unique: [true, "This username is already taken."]
  },
  email: {
    unique: [true, "This email is already in use."],
  }`

**Comment by TammamWafai** [comment]
It's good if we decide which fields are **required** and which are **optional**, and give **default values** to avoid errors when they're not provided.

5. ActivitySchema: I would keep **contactNum** a String as it may have  dashes, spaces, and plus signs.
6. Routes: the mainRoute was removed, now if the front-end team tries to run their project (http://localhost:8000/api/v1/) they get a 404 error and (GET /api/v1/ 404 60.512 ms - 20) in the back-end terminal. We may need to add it back if there is a main/landing page
7. Controllers/auth.js : It's good to use **Try, Catch** in register and login as they are async functions
8. Controllers/auth.js : line 55 module.exports = { register, login, logout }; this line was duplicated

**Comment by TammamWafai** [comment]
9. controllers/auth.js : You used (req.session) in Logout without using any session handling middleware which resulted in an error when tested it. 
I was able to fix it by adding this to App.js (after installing the package using "npm install express-session":
```
const session = require('express-session');
app.use(
  session({
    secret: process.env.JWT_SECRET, 
    resave: false,
    saveUninitialized: true,
  })
);
```
You can handle it in your way too.

**Comment by TammamWafai** [comment]
10. db/connect.js was created but not used
11. package.json: those lines should be changed:
"name": "bb-practicum-team-1-back",
  "description": "Back-End Repo for Team 1 of Baboon/Bald Eagle Practicum",
12. bb-practicum-team-1-back@1.0.0 should be removed
13. .DS_Store is a macOS file we need it in the repo it should be added to .gitignore

**Comment by TammamWafai** [comment]
14. controllers/activities.js/getAllActivities line 6: you're trying to filter the response using a field that doesn't exist "createdBy" and sort by "createdAt". For now, we can make it return all activities created by all users.
15. controllers/activities.js/getAllActivities: no authentication needed for now
16. controllers/activities.js : make sure all functions have **try and catch** as they are async 
17. controllers/activities.js/getActivity line 17: you are using a field that doesn't exist to filter activities "createdBy: userId". No need for authentication to get an activity.
18.  controllers/activities.js/deleteActivity: it's good if you make it return a confirmation message
19. controllers/activities.js/editActivity: several fields in the body don't match with the schema which causes errors.
20. controllers/activities.js/editActivity: you don't need to throw a BadRequestError("Fields cannot be empty") for optional fields if they're not provided or empty

**Comment by TammamWafai** [comment]
You've done an excellent job implementing all these functionalities. Your code appears to be mostly error-free. The 20 points mentioned earlier are valuable suggestions to enhance the project's quality and prevent potential issues down the road. It's crucial to thoroughly **test** your code before pushing it to the repository to ensure it functions as intended.

**Review by TammamWafai — APPROVED** [review]
I tested the new features on Postman and they seem to be working

**Review by benochi — APPROVED** [review]

**Pull request merged**
