### PR TITLE
Update user password route and controller

### PR DESCRIPTION
**Pull request by vitaliipp**
Update user password route and controller have been created.
Route has been tested in Postman.
Endpoint : http://localhost:8000/api/v1/users/updateUserPassword
Req body: oldPassword, newPassword

### CODE REVIEW

**Review by TammamWafai — CHANGES_REQUESTED** [review]
Nice work! It functions correctly with valid inputs. Two quick fixes for error handling:

- When a required parameter is missing, it throws: "msg": "CustomError is not defined." 
- Similar issue with an incorrect oldPassword, leading to the same error. 

Keep it up! 👍

**Comment by vitaliipp** [comment]
> Nice work! It functions correctly with valid inputs. Two quick fixes for error handling:
> 
> * When a required parameter is missing, it throws: "msg": "CustomError is not defined."
> * Similar issue with an incorrect oldPassword, leading to the same error.
> 
> Keep it up! 👍
Error messages should now be correct

**Review by TammamWafai — APPROVED** [review]
It works, and error handling works too.

**Review by oxangyal — APPROVED** [review]
LGTM

**Pull request merged**
