### PR TITLE
Forgot Password DONE

### PR DESCRIPTION
**Pull request by TammamWafai**
**Forgot password:**

POST      http://localhost:8000/api/v1/auth/forgotPassword     
Body:     { "email": "xyz@gmail.com"}
Res:        {"msg": "Reset password email sent!"}    OR    an error.

A reset password email will be sent with a button that takes you to the reset password URL:

POST    http://localhost:8000/api/v1/auth/resetPassword/1d09aa86?email=xyz@gmail.com
Body :   { "newPassword":"Xyz@123456789" } 
Res:       {"message": "Reset password successful!"}     OR  an error

The URLs will be changed once integrated with the Frontend team.

### CODE REVIEW

**Review by vitaliipp — APPROVED** [review]
Great job! Code looks clean and well-organized.

**Review by Ljanjic — CHANGES_REQUESTED** [review]
Nice job! Please correct the endpoint to {{URL}}/auth/forgotPassword, as you have misspelled now: /api/v1/auth/forgotPassOWRD). If we have time would be good to add sending a new email about successful password update.

**Comment by TammamWafai** [comment]
Changes are done!
Glad you highlighted that type @Ljanjic 
Let me know if there is anything else to fix.

**Review by Ljanjic — APPROVED** [review]
Great!

**Pull request merged**
