### PR TITLE
Sorting activitites

### PR DESCRIPTION
**Pull request by Ljanjic**
Activities are sorted by dates, showing activities today, and upcoming activities.
Activities searched by Zip Code sorted by date and distance (25-mile radius).
Earlier "getAMyActivities" were representing "created activities", but for clarity I renamed and changed the end point, so now we have : 
Created ||        Joined ||           AllActivitites(=> all other activities, created and joined excluded) : 
createdActivities: GET: {{URL}}/activities/createdActivities/:userId,  
joinedActivities: GET: {{URL}}/activities/joinedActivities/:userId, 
allActivities: GET: {{URL}}/activities/allOtherActivities/:userId

### CODE REVIEW

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Great job, but our app does not display any activities on the main page
image

**Review by vitaliipp — APPROVED** [review]
I know you faced some challenges with this PR, but your persistence paid off. Great resilience!

**Review by vitaliipp — CHANGES_REQUESTED** [review]
Something went wrong
image

**Review by vitaliipp — APPROVED** [review]

**Review by TammamWafai — CHANGES_REQUESTED** [review]
I tested this, I joined two activities and made this request:
GET   {{URL}}/activities/joinedActivities/6577548c96578a5e35f065e8

And the response was:
{    "message": "You have 0 joined activities today, and 1 upcoming activity. ",
    "activitiesToday": [],
    "upcomingActivities": [
        {
        ...
        }
    ]
}

**Shouldn't this show both of the activities I joined?**

image
image

**Comment by Ljanjic** [comment]
@TammamWafai One activity is passed, so Past Activities we do not show

**Comment by TammamWafai** [comment]
@Ljanjic you're right! Great job!

There is one thing, when I tried to get all other activities, it didn't show an activity which has today's date and will happen after a few hours from now:
GET    {{URL}}/activities/allOtherActivities/6577548c96578a5e35f065e8
RES:   "message": "Pickleball app have _**0 activities**_ today, and 15 upcoming activities. ",

image
image

**Comment by Ljanjic** [comment]
@TammamWafai , in allOtherActivitites you will not show activities you have created or joined, so if you were checking as a User who created or joined that activity, you can find it only in Created/Joined activities. If that was not the case when you checked, please, let me know, thanks

**Comment by TammamWafai** [comment]
For some reason, it shows that I didn't join any activities after I joined 2:
image
image

Kindly advise.

**Comment by Ljanjic** [comment]
@TammamWafai, the second activity passed, and on the app, past activities will not be shown, so users will not be able to join an activity that already happened.

**Comment by TammamWafai** [comment]
Can you add this line: 
`     console.log(
      'Created Activities: ',
      activities,
      '\nToday Activities: ',
      activitiesToday,
      '\nUpcoming Activities : ',
      upcomingActivities,
    );`
    
    after this line:
    `   const upcomingActivities = activities.filter((activity) => new Date(activity.date) > currentDate);`
    
    That way you can see where the bug is and fix it in 'activityController.js - getCreatedActivities'

**Comment by TammamWafai** [comment]
The same with 'activityController.js - getJoinedActivities', you can add this line:

`     console.log(
      'Joined Activities: ',
      joinedActivities,
      '\nToday Activities: ',
      activitiesToday,
      '\nUpcoming Activities : ',
      upcomingActivities,
    );`
    
After this line:

`   const upcomingActivities = joinedActivities.filter((activity) => new Date(activity.date) > currentDate);`

That will help you find the bug in that function.

**Review by TammamWafai — APPROVED** [review]

**Comment by TammamWafai** [comment]
Approved upon the FE request as they needed it.
There is still some work to be done to fix the logic of the code and return the correct result, especially for the results related to same-day activities.
@Ljanjic @benochi

**Pull request merged**
